services:

  backend:
    build: .
    container_name: file-manager-api
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
    restart: unless-stopped

  frontend:
    build:
      context: ../helpdesk-front
    container_name: file-manager-web
    ports:
      - "4200:80"
    depends_on:
      - backend
    restart: unless-stopped